on: push
jobs: 
  build-python:
    runs-on: ubuntu-latest
    container: python:3.10
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3
      - name: Verificar versión de Python
        run: python --version

